Repository YAPP-admin/yappu-world-android, pull requests merged in 2025-05, with the labels that each got.

#160 Feature/#159 : 사용자가 출석체크 코드 백버튼 제거 시 이전 텍스트 필드로 포커싱 가도록 처리
  feature/home/src/main/java/com/yapp/feature/home/dialog/AttendanceDialog.kt
Labels: Feature, CodeRabbit

#196 fix/#195: 앱 기본 폰트 크기 1.0f로 고정
  app/src/main/java/com/yapp/app/official/MainActivity.kt
  app/src/main/java/com/yapp/app/official/YappOfficialApplication.kt
Labels: Bug

#197 Feature/#194: 출석 완료 상태에 따라 버튼 노출 메세지 변경
  feature/home/src/main/java/com/yapp/feature/home/component/HomeAttendanceContent.kt
  feature/home/src/main/res/values/strings.xml
Labels: Feature

#199 [Chore] Fastlane을 통한 Firebase App Distribution 스크립트 작성
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: Chore
